services:
  kohya_ss-rocm:
    build: 
      context: .
      dockerfile: Dockerfile.rocm
    container_name: kohya_ss-rocm-runner
    environment:
      TZ: "Asia/Jakarta"
      ROC_ENABLE_PRE_VEGA: 1
      COMMANDLINE_ARGS: "--listen 0.0.0.0 --server_port 7860 --headless"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "rocm-smi; . /kohya_ss.env; echo kohya_gui.py $$COMMANDLINE_ARGS;
      if [ ! -d /kohya_ss/.git ]; then
        cp -a /sdtemp/. /kohya_ss/
      fi;
      /usr/bin/python3 kohya_gui.py $$COMMANDLINE_ARGS"
    ports:
      - "7860:7860"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./kohya_ss.env:/kohya_ss.env
      - ./kohya_ss:/kohya_ss
      - ./config:/config
      - ./dataset:/dataset
